name: Zbuduj plik IPA (Sideloadly)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Kompilowanie IPA w Xcode
    runs-on: macos-latest

    steps:
      - name: Pobieranie plikow z repozytorium
        uses: actions/checkout@v4

      # 1. Pobieranie Godota 4.6
      - name: Pobierz i zainstaluj Godot 4.6
        run: |
          curl -LO https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_macos.universal.zip
          unzip Godot_v4.6-stable_macos.universal.zip
          mv Godot.app /Applications/Godot.app
          rm Godot_v4.6-stable_macos.universal.zip

      # 2. Pobieranie oficjalnych szablonów eksportu
      - name: Pobierz szablony eksportu Godota
        run: |
          mkdir -p "$HOME/Library/Application Support/Godot/export_templates/4.6.stable"
          curl -LO https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
          mv Godot_v4.6-stable_export_templates.tpz templates.zip
          unzip templates.zip
          mv templates/* "$HOME/Library/Application Support/Godot/export_templates/4.6.stable/"
          rm -rf templates templates.zip

      # 3. Eksportowanie projektu z Godota do Xcode
      - name: Eksport do Xcode
        run: |
          mkdir -p build/ios
          # Dodajemy '|| true', aby zignorować błąd automatycznej kompilacji Godota. 
          # Projekt Xcode i tak zdąży się wygenerować!
          /Applications/Godot.app/Contents/MacOS/Godot --headless --export-release "iOS" build/ios/gowno.xcodeproj || true

      # 4. Kompilowanie pliku za pomocą Xcode
      - name: Kompilowanie pliku .ipa za pomoca darmowego Xcode
        run: |
          cd build/ios
          # Dodano CODE_SIGN_STYLE="Manual", aby Xcode nie pluł się o ustawienia wygenerowane przez Godota
          xcodebuild build -project gowno.xcodeproj -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_STYLE="Manual"
          mkdir -p Payload
          mv build/Release-iphoneos/*.app Payload/
          zip -r ../../Gra_gotowa_sideloadly.ipa Payload
          
      # 5. Udostępnienie gotowego pliku IPA do pobrania
      - name: Udostepnianie gotowego pliku IPA do pobrania
        uses: actions/upload-artifact@v4
        with:
          name: Gra-Na-iPhone-Sideloadly
          path: Gra_gotowa_sideloadly.ipa